### ISSUE TITLE
Android, iOSで動作しない件について

### ISSUE THREAD

**Issue by robin-kirisame** [Nyateppu-miyabi/esora_noberugame_kari#1]
いきなりすみません。
ノベルゲームのデモ作成おつかれさまです。

先日公表されたデモ版で、スマートフォン上での動作について、気付いたことがあったのでお知らせします(もし対応済みでしたらすみません)

現状、音源に.oggファイルを指定しているようですが、これらはスマートフォンだと再生できないファイル形式のようです。これにより、音源再生できず、画面表示はそのままで落ちてしまっているようです。
音源を.mp3形式にしたらスマートフォンでもタイトル画面から先に動作しました(全部は確認してないです)

**Comment by Nyateppu-miyabi** [comment]
> いきなりすみません。 ノベルゲームのデモ作成おつかれさまです。
> 
> 先日公表されたデモ版で、スマートフォン上での動作について、気付いたことがあったのでお知らせします(もし対応済みでしたらすみません)
> 
> 現状、音源に.oggファイルを指定しているようですが、これらはスマートフォンだと再生できないファイル形式のようです。これにより、音源再生できず、画面表示はそのままで落ちてしまっているようです。 音源を.mp3形式にしたらスマートフォンでもタイトル画面から先に動作しました(全部は確認してないです)

ありがとうございます！修正しておきました！

**Comment by robin-kirisame** [comment]
ご対応ありがとうございます、修正と動作することを確認できましたので本件はClosedとします
